- name: Setup sonar scanner
  uses: warchant/setup-sonar-scanner@v3

- name: Run Sonarqube analysis
  run: |
    sonar-scanner \
      -Dsonar.qualitygate.wait=true \
      -Dsonar.host.url=${{ process.env.SONAR_URL }} \
      -Dsonar.login=${{ process.env.SONAR_TOKEN }} \
      -Dsonar.projectKey=${{ process.env.SONAR_PROJECT }} \
      -Dsonar.scm.provider=git \
      -Dsonar.java.binaries=/tmp \
      -Dsonar.nodejs.executable=$(which node) \
      -Dsonar.projectVersion=$(echo $GITHUB_SHA | cut -c1-8) \
      -Dsonar.sources=. \
      -Dsonar.projectBaseDir=. \
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
