name: Setup sonar scanner
uses: warchant/setup-sonar-scanner@v3

name: Run Sonarqube analysis
  run:
    sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.host.url=https://sonarqube-developers.rootstrap.net
      -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
      -Dsonar.scm.provider=git
      -Dsonar.java.binaries=/tmp
      -Dsonar.nodejs.executable=$(which node)
      -Dsonar.projectVersion=$(echo $GITHUB_SHA | cut -c1-8)
      -Dsonar.sources=.
      -Dsonar.projectBaseDir=.
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
